identifier: mc34r9k3q8a3kf83
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: viktoriya-gonch
homeFolder: C:\Users\4sv\Desktop\vіktorіya-gonch
distFolder: ./dist/viktoriya-gonch/browser
outDir: C:\Users\4sv\Desktop\vіktorіya-gonch\dist\static
handle404: ''
allowErrorCollect: true
